version: '3'

services:
  postgresql:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_DB: vitronicdb
      POSTGRES_USER: vitronic
      POSTGRES_PASSWORD: vitronicpasswd
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/vitronic:/var/lib/postgresql/data
