version: '3'

services:
  postgresql:
    image: postgres:alpine3.18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: vitronicdb
      POSTGRES_USER: vitronic
      POSTGRES_PASSWORD: vitronicpasswd
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/vitronic:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vitronic@vitronic.de
      PGADMIN_DEFAULT_PASSWORD: vitronic
    ports:
      - "8080:80"
    depends_on:
      - postgresql
